name: Project CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      node-version: [16.15.1]

    steps:
      - name: Check Out Source Code.
      - uses: actions/checkout@v3

      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1

      - name: Package Install
        working-directory: ./src
        run: yarn

      - name: Source Code Build
        working-directory: ./src
        run: yarn build
